### PR TITLE
Support for exporting Maven artefact

### PR DESCRIPTION
**Pull request by bgermann**
Using com.github.dcendents:android-maven-gradle-plugin
one can use "gradle install" to export a Maven artefact.

### CODE REVIEW

**Comment by d-kunin** [comment]
Thanks for the PR @bgermann! Could please explain in more details what is it for and how to use it? Does it install an artifact to the local maven repo?

**Comment by bgermann** [comment]
Yes, that is right. It exports a local Maven artefact. I think it is bad to manually copy the aar to your app's directory if you use Maven or gradle, which should be true for most Android apps out there.

Maybe you want to make the artefact available on one of the common Maven repositories so that you can just point people interested in this library to it without manually downloading/building it.

**Comment by bgermann** [comment]
You have to use ID `com.spotify.sdk:spotify-android-auth:1.0.0@aar` in your project to import it (mind the version number is a gradle version number, not part of the name as in your manually built aar).

**Comment by bgermann** [comment]
You can see that there is a need for such an artefact by looking at e.g. https://github.com/wireapp/wire-android-sync-engine/blob/develop/external/build.sbt where the wire people create a maven artefact themselves which they publish at https://dl.bintray.com/wire-android/third-party

**Pull request merged**
