### PR TITLE
Fix StackOverflowError and bump library to 2.0.2

### PR DESCRIPTION
**Pull request by veronikapetruskova**
## Changes in version 2.0.2
- Fixed StackOverflowError - `TabConnection#onServiceDisconnected` was called as a reaction to Tab service being disconnected which lead to calling it in an infinite loop.
- Fixed NullPointerException when creating `CustomTabsIntent` in LoginDialog - creating CustomTabsSession might fail in which case the session will be null. We need to check for this and launch authorization in browser instead as a fallback solution.
- Set LoginActivity launch mode to singleTask to avoid launching CustomTabs in a separate task

### CODE REVIEW

**Comment by veronikapetruskova** [comment]
@pimpimmi

**Comment by aaronfodor** [comment]
Dear @veronikapetruskova,

I recently encountered a problem with Spotify Auth Lib 2.0.1 which is in my oppinion related to this issue - few of my users got null pointer exception from 

https://github.com/spotify/android-auth/blob/94dbccc8ab4935154d1a27897ccddfa04876e871/auth-lib/src/main/java/com/spotify/sdk/android/auth/browser/LoginDialog.java#L167

Now I see that the callback implementation changed slightly in this PR, but `mTabsSession` still does not have a null check and I think my issue way explicitly caused by that. I could not reproduce it on my device though, I only see the problem via Firebase (the affected devices were running Android 9-10-11).

null

If this null pointed-related issue has already been resolved in this PR then consider what I wrote to be irrelevant, but I wanted to draw attention to this.

**Comment by veronikapetruskova** [comment]
Hi @aaronfodor I'll take a look since I'm not sure my changes will avoid the NullPointerException you had.

**Review by pimpimmi — APPROVED** [review]
LGTM 👍

**Review by pimpimmi — APPROVED** [review]

**Pull request merged**
